```{r,echo=FALSE}
unicos<-read.csv("C:/Users/GIC 14/Documents/tmp/registrosUnicos.csv")
tnames_long <- c("Minimum.training.presence.logistic.threshold","X10.percentile.training.presence.logistic.threshold","Equal.training.sensitivity.and.specificity.logistic.threshold","Maximum.training.sensitivity.plus.specificity.logistic.threshold")
spName = "Abarema_barbouriana"
spName2 = gsub("_"," ",spName)
df = read.csv(paste0("W:/Visor/20131122/CSV/",spName,".csv"))
load(paste0("W:/Modelos/20131122/",spName,".RData"))
```
Modelo de distribución de *`r spName2`*
========================================================

Datos de distribución
--------------------------------------------------------
Descargados de GBIF:  (http://data.gbif.org)  
Descargados de SIB Colombia:   (http://data.sibcolombia.net)  
Registros únicos:  `r unicos[which(unicos$Especie==spName),2]`  
Disponibles en: `r spName`.csv

Datos ambientales
--------------------------------------------------------
Tomados de [WorldClim](http://worldclim.org) 

BIO1 = Temperatura media anual  
BIO2 = Rango de temperatura diurna promedio anual  
BIO3 = Isotermalidad (BIO2/BIO7 * 100)  
BIO4 = Estacionalidad de la temperatura (desviación estandard * 100)  
BIO5 = Máxima temperatura del mes más cálido  
BIO6 = Mínima temperatura del mes más frio  
BIO7 = Rango de temperatura anual (BIO5-BIO6)  
BIO8 = Temperatura promedio del trimestre más húmedo  
BIO9 = Temperatura promedio del trimestre más seco  
BIO10 = Temperatura promedio del trimestre más cálido  
BIO11 = Temperatura promedio del trimestre más frío  
BIO12 = Precipitación anual  
BIO13 = Precipitación del mes más húmedo  
BIO14 = Precipitación del mes más seco  
BIO15 = Estacionalidad de la precipitación (coeficiente de variación)  
BIO16 = Precipitación del trimestre más húmedo  
BIO17 = Precipitación del trimestre más seco  
BIO18 = Precipitación del trimestre más cálido  
BIO19 = Precipitación del trimestre más frio  

Parámetros de modelamiento
--------------------------------------------------------
Metodo de modelamiento: MAXENT 3.3.3k (Phillips et al. 2006)

Background: 10000 puntos aleatorios.

### Configuración  
Linear = TRUE  
Quadratic = TRUE  
Hinge = TRUE  
Product = FALSE  
Threshold = FALSE  
Auto = FALSE  
Extrapolate = FALSE  
Clamp = FALSE  

### Umbrales
Mínima presencia de los datos de entrenamiento (min) =  `r as.numeric(mxnt.obj@results[tnames_long[1],])`  
Décimo percentil de presencia de los datos de entrenamiento (10p) =  `r as.numeric(mxnt.obj@results[tnames_long[1],])`  
Igual sensibilidad y especificidad de los datos de entrenamiento  (ess) =  `r as.numeric(mxnt.obj@results[tnames_long[3],])`  
Máxima suma de sensibilidad y especificidad de los datos de entrenamiento (mss) =  `r as.numeric(mxnt.obj@results[tnames_long[4],])`  

Créditos
--------------------------------------------------------
Instituciones proveedoras de datos: `r paste(sort(unique(df$institution)),collapse=", ")`

Colectores/Observadores: `r paste(sort(unique(df$collector)),collapse=", ")`

Modelo desarrollado por:  
> Jorge Velásquez-Tibatá  
> Laboratorio de Biogeografía Aplicada y Bioacústica (LBAB)  
> Instituto Alexander von Humboldt  
> Bogotá, Colombia  
> (jvelasquez@humboldt.org.co)  

Fecha desarrollo:	2013-11-22

Cómo citar un modelo:	

> Laboratorio de Biogeografía Aplicada y Bioacústica. 2013. Modelo de distribución de *`r spName2`*. Instituto Alexander von Humboldt. http://biomodelos.humboldt.org.co.
 
Cómo citar un conjunto de modelos:	

> Laboratorio de Biogeografía Aplicada y Bioacústica. 2013. Biomodelos. Instituto Alexander von Humboldt. http://biomodelos.humboldt.org.co.

Contacto:
> Maria C. Londoño 
> mlondono@humboldt.org.co